"""Human-readable diagnostics derived from Yada JSONL traces."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from yada.traces.jsonl import TRACE_SCHEMA_VERSION


class TraceFormatError(ValueError):
    """Raised when a JSONL trace contains an invalid event record."""


def read_trace(path: Path) -> list[dict[str, Any]]:
    """Load and minimally validate all events in a trace file.

    Args:
        path: UTF-8 JSONL trace generated by :class:`TraceWriter`.

    Returns:
        Event dictionaries in file order. Legacy records without correlation
        metadata are accepted so older runs remain inspectable.

    Raises:
        TraceFormatError: If a non-empty line is not a valid event object.
        OSError: If the trace cannot be read.
    """

    events: list[dict[str, Any]] = []
    lines = path.read_text(encoding="utf-8").splitlines()
    for line_number, line in enumerate(lines, 1):
        if not line.strip():
            continue
        try:
            record = json.loads(line)
        except json.JSONDecodeError as exc:
            raise TraceFormatError(
                f"line {line_number}: invalid JSON: {exc.msg}"
            ) from exc
        if not isinstance(record, dict) or not isinstance(record.get("event"), str):
            raise TraceFormatError(
                f"line {line_number}: expected an object with a string event field"
            )
        if not isinstance(record.get("data"), dict):
            raise TraceFormatError(f"line {line_number}: data must be an object")
        schema_version = record.get("schema_version")
        if isinstance(schema_version, int) and schema_version > TRACE_SCHEMA_VERSION:
            raise TraceFormatError(
                f"line {line_number}: trace schema {schema_version} is newer than "
                f"supported schema {TRACE_SCHEMA_VERSION}"
            )
        events.append(record)
    if not events:
        raise TraceFormatError("trace contains no events")
    return events


def reconstruct_model_request(
    events: list[dict[str, Any]],
    step: int,
) -> dict[str, Any]:
    """Return the sanitized provider payload captured for one model turn.

    Summary and legacy traces intentionally lack this payload. Callers receive a
    clear error instead of a partial reconstruction assembled from source code.
    """

    request = next(
        (
            event
            for event in events
            if event["event"] == "model_request" and event["data"].get("step") == step
        ),
        None,
    )
    if request is None:
        raise TraceFormatError(f"trace contains no model request for step {step}")
    payload = request["data"].get("payload")
    if not isinstance(payload, dict):
        raise TraceFormatError(
            f"step {step} has no captured model payload; rerun with --trace-level debug"
        )
    return payload


def render_trace_report(
    path: Path,
    *,
    step: int | None = None,
    verbose: bool = False,
) -> str:
    """Render a compact run summary and chronological event timeline.

    The report intentionally summarizes large prompts, arguments, and command
    output instead of echoing them. The original JSONL remains available when a
    specific payload needs deeper inspection.

    Args:
        path: Trace file to inspect.

    Returns:
        Plain text suitable for a terminal, issue, or interview walkthrough.
    """

    events = read_trace(path)
    timeline_events = events
    if step is not None:
        timeline_events = [
            event for event in events if event["data"].get("step") == step
        ]
        if not timeline_events:
            raise TraceFormatError(f"trace contains no events for step {step}")
    start = _first_event(events, "run_start")
    end = _first_event(reversed(events), "run_end")
    model_turns = sum(event["event"] == "assistant" for event in events)
    tool_results = [event for event in events if event["event"] == "tool_result"]
    tool_failures = sum(
        not bool(event["data"].get("result", {}).get("ok")) for event in tool_results
    )
    reminders = sum(event["event"] == "protocol_reminder" for event in events)
    last_elapsed = max(
        (
            event.get("elapsed_ms", 0)
            for event in events
            if isinstance(event.get("elapsed_ms"), int)
        ),
        default=0,
    )

    start_data = start["data"] if start else {}
    end_data = end["data"] if end else {}
    run_id = next(
        (event.get("run_id") for event in events if event.get("run_id")),
        "legacy",
    )
    outcome = (
        "finished"
        if end_data.get("finished") is True
        else "unfinished"
        if end
        else "interrupted (no run_end event)"
    )
    lines = [
        "Yada trace report",
        f"Path: {path}",
        f"Run: {run_id}",
        f"Model: {start_data.get('model', 'unknown')}",
        f"Trace level: {start_data.get('trace_level', 'legacy')}",
        f"Task: {_one_line(start_data.get('task', 'unknown'), 160)}",
        f"Outcome: {outcome}",
        (
            "Totals: "
            f"{model_turns} model turns, {len(tool_results)} tool results, "
            f"{tool_failures} tool failures, {reminders} reminders, {last_elapsed} ms"
        ),
        f"Timeline{f' (step {step})' if step is not None else ''}:",
    ]
    detailed = verbose or step is not None
    for fallback_sequence, event in enumerate(timeline_events, 1):
        sequence = event.get("sequence", fallback_sequence)
        elapsed = event.get("elapsed_ms", "?")
        lines.append(f"  [{sequence!s:>3} +{elapsed!s:>6}ms] {_describe_event(event)}")
        if detailed:
            if event["event"] == "model_request" and "payload" not in event["data"]:
                lines.append(
                    "      payload unavailable: rerun with --trace-level debug"
                )
            rendered = json.dumps(
                event["data"],
                ensure_ascii=False,
                indent=2,
                sort_keys=True,
                default=str,
            )
            lines.extend(f"      {line}" for line in rendered.splitlines())
    return "\n".join(lines) + "\n"


def _first_event(events, name: str) -> dict[str, Any] | None:
    return next((event for event in events if event["event"] == name), None)


def _describe_event(event: dict[str, Any]) -> str:
    name = event["event"]
    data = event["data"]
    step = data.get("step")
    step_text = f"step={step} " if step is not None else ""
    if name == "run_start":
        return f"run_start workspace={_one_line(data.get('workspace', '?'), 80)}"
    if name == "model_request":
        context = data.get("context") or {}
        return (
            f"{step_text}model_request messages={context.get('message_count', '?')} "
            f"chars={context.get('serialized_chars', '?')}"
        )
    if name == "assistant":
        message = data.get("message") or {}
        calls = message.get("tool_calls") or []
        names = ",".join(
            str((call.get("function") or {}).get("name") or "<missing>")
            for call in calls
        )
        usage = data.get("usage") or {}
        tokens = usage.get("total_tokens")
        token_text = f" tokens={tokens}" if isinstance(tokens, int) else ""
        return (
            f"{step_text}assistant duration={data.get('duration_ms', '?')}ms "
            f"finish={data.get('finish_reason', '?')} tools={names or '-'}{token_text}"
        )
    if name == "model_error":
        return (
            f"{step_text}model_error {data.get('error_type', 'Error')}: "
            f"{_one_line(data.get('error', ''), 120)}"
        )
    if name == "plan_decision":
        tools = ",".join(str(tool) for tool in (data.get("tools") or []))
        detail = ""
        if data.get("rejection_error"):
            detail = f" rejected={_one_line(data['rejection_error'], 100)}"
        return (
            f"{step_text}plan_decision action={data.get('action', '?')} "
            f"tools={tools or '-'}{detail}"
        )
    if name == "tool_call":
        arguments = data.get("arguments")
        if data.get("rejected"):
            keys = "rejected"
        else:
            keys = ",".join(sorted(arguments)) if isinstance(arguments, dict) else "raw"
        return (
            f"{step_text}tool_call id={data.get('tool_call_id', '?')} "
            f"tool={data.get('tool', '?')} args={keys or '-'}"
        )
    if name == "tool_result":
        result = data.get("result") or {}
        status = "ok" if result.get("ok") else "error"
        detail = ""
        if not result.get("ok"):
            detail = f" detail={_one_line(result.get('error', 'unknown error'), 120)}"
        elif "exit_code" in result:
            detail = f" exit={result.get('exit_code')}"
        return (
            f"{step_text}tool_result id={data.get('tool_call_id', '?')} "
            f"tool={data.get('tool', '?')} status={status} "
            f"duration={data.get('duration_ms', '?')}ms{detail}"
        )
    if name == "protocol_reminder":
        return f"{step_text}protocol_reminder"
    if name == "protocol_violation":
        return f"{step_text}protocol_violation {_one_line(data.get('error', ''), 120)}"
    if name == "run_end":
        return (
            f"run_end finished={data.get('finished')} steps={data.get('steps')} "
            f"summary={_one_line(data.get('summary', ''), 120)}"
        )
    return f"{step_text}{name}"


def _one_line(value: Any, limit: int) -> str:
    text = " ".join(str(value).split())
    return text if len(text) <= limit else text[: limit - 1] + "…"
